// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

#ifndef PROTOBUF_login_2eproto__INCLUDED
#define PROTOBUF_login_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace login {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_login_2eproto();
void protobuf_AssignDesc_login_2eproto();
void protobuf_ShutdownFile_login_2eproto();

class Login_EmailLogin_Request_22;
class Login_EmailLogin_Response_22;
class Login_GetEmailCode_Request_1;
class Login_GetEmailCode_Response_1;
class Login_RegisterEmail_Request_11;
class Login_RegisterEmail_Response_11;
class Login_UserIdLogin_Request_21;
class Login_UserIdLogin_Response_21;
class Login_keyLogin_Request_25;
class Login_keyLogin_Response_25;

// ===================================================================

class Login_GetEmailCode_Request_1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_GetEmailCode_Request_1) */ {
 public:
  Login_GetEmailCode_Request_1();
  virtual ~Login_GetEmailCode_Request_1();

  Login_GetEmailCode_Request_1(const Login_GetEmailCode_Request_1& from);

  inline Login_GetEmailCode_Request_1& operator=(const Login_GetEmailCode_Request_1& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_GetEmailCode_Request_1& default_instance();

  void Swap(Login_GetEmailCode_Request_1* other);

  // implements Message ----------------------------------------------

  inline Login_GetEmailCode_Request_1* New() const { return New(NULL); }

  Login_GetEmailCode_Request_1* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Login_GetEmailCode_Request_1& from);
  void MergeFrom(const Login_GetEmailCode_Request_1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Login_GetEmailCode_Request_1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string email = 1;
  void clear_email();
  static const int kEmailFieldNumber = 1;
  const ::std::string& email() const;
  void set_email(const ::std::string& value);
  void set_email(const char* value);
  void set_email(const char* value, size_t size);
  ::std::string* mutable_email();
  ::std::string* release_email();
  void set_allocated_email(::std::string* email);

  // @@protoc_insertion_point(class_scope:login.Login_GetEmailCode_Request_1)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr email_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static Login_GetEmailCode_Request_1* default_instance_;
};
// -------------------------------------------------------------------

class Login_GetEmailCode_Response_1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_GetEmailCode_Response_1) */ {
 public:
  Login_GetEmailCode_Response_1();
  virtual ~Login_GetEmailCode_Response_1();

  Login_GetEmailCode_Response_1(const Login_GetEmailCode_Response_1& from);

  inline Login_GetEmailCode_Response_1& operator=(const Login_GetEmailCode_Response_1& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_GetEmailCode_Response_1& default_instance();

  void Swap(Login_GetEmailCode_Response_1* other);

  // implements Message ----------------------------------------------

  inline Login_GetEmailCode_Response_1* New() const { return New(NULL); }

  Login_GetEmailCode_Response_1* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Login_GetEmailCode_Response_1& from);
  void MergeFrom(const Login_GetEmailCode_Response_1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Login_GetEmailCode_Response_1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ErrorCode = 1;
  void clear_errorcode();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 errorcode() const;
  void set_errorcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:login.Login_GetEmailCode_Response_1)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 errorcode_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static Login_GetEmailCode_Response_1* default_instance_;
};
// -------------------------------------------------------------------

class Login_RegisterEmail_Request_11 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_RegisterEmail_Request_11) */ {
 public:
  Login_RegisterEmail_Request_11();
  virtual ~Login_RegisterEmail_Request_11();

  Login_RegisterEmail_Request_11(const Login_RegisterEmail_Request_11& from);

  inline Login_RegisterEmail_Request_11& operator=(const Login_RegisterEmail_Request_11& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_RegisterEmail_Request_11& default_instance();

  void Swap(Login_RegisterEmail_Request_11* other);

  // implements Message ----------------------------------------------

  inline Login_RegisterEmail_Request_11* New() const { return New(NULL); }

  Login_RegisterEmail_Request_11* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Login_RegisterEmail_Request_11& from);
  void MergeFrom(const Login_RegisterEmail_Request_11& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Login_RegisterEmail_Request_11* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string code = 1;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  const ::std::string& code() const;
  void set_code(const ::std::string& value);
  void set_code(const char* value);
  void set_code(const char* value, size_t size);
  ::std::string* mutable_code();
  ::std::string* release_code();
  void set_allocated_code(::std::string* code);

  // optional string email = 2;
  void clear_email();
  static const int kEmailFieldNumber = 2;
  const ::std::string& email() const;
  void set_email(const ::std::string& value);
  void set_email(const char* value);
  void set_email(const char* value, size_t size);
  ::std::string* mutable_email();
  ::std::string* release_email();
  void set_allocated_email(::std::string* email);

  // optional string name = 3;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string pass = 4;
  void clear_pass();
  static const int kPassFieldNumber = 4;
  const ::std::string& pass() const;
  void set_pass(const ::std::string& value);
  void set_pass(const char* value);
  void set_pass(const char* value, size_t size);
  ::std::string* mutable_pass();
  ::std::string* release_pass();
  void set_allocated_pass(::std::string* pass);

  // @@protoc_insertion_point(class_scope:login.Login_RegisterEmail_Request_11)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr code_;
  ::google::protobuf::internal::ArenaStringPtr email_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr pass_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static Login_RegisterEmail_Request_11* default_instance_;
};
// -------------------------------------------------------------------

class Login_RegisterEmail_Response_11 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_RegisterEmail_Response_11) */ {
 public:
  Login_RegisterEmail_Response_11();
  virtual ~Login_RegisterEmail_Response_11();

  Login_RegisterEmail_Response_11(const Login_RegisterEmail_Response_11& from);

  inline Login_RegisterEmail_Response_11& operator=(const Login_RegisterEmail_Response_11& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_RegisterEmail_Response_11& default_instance();

  void Swap(Login_RegisterEmail_Response_11* other);

  // implements Message ----------------------------------------------

  inline Login_RegisterEmail_Response_11* New() const { return New(NULL); }

  Login_RegisterEmail_Response_11* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Login_RegisterEmail_Response_11& from);
  void MergeFrom(const Login_RegisterEmail_Response_11& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Login_RegisterEmail_Response_11* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ErrorCode = 1;
  void clear_errorcode();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 errorcode() const;
  void set_errorcode(::google::protobuf::int32 value);

  // optional int64 userId = 2;
  void clear_userid();
  static const int kUserIdFieldNumber = 2;
  ::google::protobuf::int64 userid() const;
  void set_userid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:login.Login_RegisterEmail_Response_11)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 userid_;
  ::google::protobuf::int32 errorcode_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static Login_RegisterEmail_Response_11* default_instance_;
};
// -------------------------------------------------------------------

class Login_UserIdLogin_Request_21 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_UserIdLogin_Request_21) */ {
 public:
  Login_UserIdLogin_Request_21();
  virtual ~Login_UserIdLogin_Request_21();

  Login_UserIdLogin_Request_21(const Login_UserIdLogin_Request_21& from);

  inline Login_UserIdLogin_Request_21& operator=(const Login_UserIdLogin_Request_21& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_UserIdLogin_Request_21& default_instance();

  void Swap(Login_UserIdLogin_Request_21* other);

  // implements Message ----------------------------------------------

  inline Login_UserIdLogin_Request_21* New() const { return New(NULL); }

  Login_UserIdLogin_Request_21* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Login_UserIdLogin_Request_21& from);
  void MergeFrom(const Login_UserIdLogin_Request_21& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Login_UserIdLogin_Request_21* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 userId = 1;
  void clear_userid();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::int64 userid() const;
  void set_userid(::google::protobuf::int64 value);

  // optional string pass = 2;
  void clear_pass();
  static const int kPassFieldNumber = 2;
  const ::std::string& pass() const;
  void set_pass(const ::std::string& value);
  void set_pass(const char* value);
  void set_pass(const char* value, size_t size);
  ::std::string* mutable_pass();
  ::std::string* release_pass();
  void set_allocated_pass(::std::string* pass);

  // @@protoc_insertion_point(class_scope:login.Login_UserIdLogin_Request_21)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 userid_;
  ::google::protobuf::internal::ArenaStringPtr pass_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static Login_UserIdLogin_Request_21* default_instance_;
};
// -------------------------------------------------------------------

class Login_UserIdLogin_Response_21 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_UserIdLogin_Response_21) */ {
 public:
  Login_UserIdLogin_Response_21();
  virtual ~Login_UserIdLogin_Response_21();

  Login_UserIdLogin_Response_21(const Login_UserIdLogin_Response_21& from);

  inline Login_UserIdLogin_Response_21& operator=(const Login_UserIdLogin_Response_21& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_UserIdLogin_Response_21& default_instance();

  void Swap(Login_UserIdLogin_Response_21* other);

  // implements Message ----------------------------------------------

  inline Login_UserIdLogin_Response_21* New() const { return New(NULL); }

  Login_UserIdLogin_Response_21* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Login_UserIdLogin_Response_21& from);
  void MergeFrom(const Login_UserIdLogin_Response_21& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Login_UserIdLogin_Response_21* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ErrorCode = 1;
  void clear_errorcode();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 errorcode() const;
  void set_errorcode(::google::protobuf::int32 value);

  // optional int64 userId = 2;
  void clear_userid();
  static const int kUserIdFieldNumber = 2;
  ::google::protobuf::int64 userid() const;
  void set_userid(::google::protobuf::int64 value);

  // optional string key = 3;
  void clear_key();
  static const int kKeyFieldNumber = 3;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // optional string ip = 4;
  void clear_ip();
  static const int kIpFieldNumber = 4;
  const ::std::string& ip() const;
  void set_ip(const ::std::string& value);
  void set_ip(const char* value);
  void set_ip(const char* value, size_t size);
  ::std::string* mutable_ip();
  ::std::string* release_ip();
  void set_allocated_ip(::std::string* ip);

  // optional uint32 port = 5;
  void clear_port();
  static const int kPortFieldNumber = 5;
  ::google::protobuf::uint32 port() const;
  void set_port(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:login.Login_UserIdLogin_Response_21)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 userid_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::int32 errorcode_;
  ::google::protobuf::uint32 port_;
  ::google::protobuf::internal::ArenaStringPtr ip_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static Login_UserIdLogin_Response_21* default_instance_;
};
// -------------------------------------------------------------------

class Login_EmailLogin_Request_22 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_EmailLogin_Request_22) */ {
 public:
  Login_EmailLogin_Request_22();
  virtual ~Login_EmailLogin_Request_22();

  Login_EmailLogin_Request_22(const Login_EmailLogin_Request_22& from);

  inline Login_EmailLogin_Request_22& operator=(const Login_EmailLogin_Request_22& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_EmailLogin_Request_22& default_instance();

  void Swap(Login_EmailLogin_Request_22* other);

  // implements Message ----------------------------------------------

  inline Login_EmailLogin_Request_22* New() const { return New(NULL); }

  Login_EmailLogin_Request_22* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Login_EmailLogin_Request_22& from);
  void MergeFrom(const Login_EmailLogin_Request_22& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Login_EmailLogin_Request_22* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string email = 1;
  void clear_email();
  static const int kEmailFieldNumber = 1;
  const ::std::string& email() const;
  void set_email(const ::std::string& value);
  void set_email(const char* value);
  void set_email(const char* value, size_t size);
  ::std::string* mutable_email();
  ::std::string* release_email();
  void set_allocated_email(::std::string* email);

  // optional string pass = 2;
  void clear_pass();
  static const int kPassFieldNumber = 2;
  const ::std::string& pass() const;
  void set_pass(const ::std::string& value);
  void set_pass(const char* value);
  void set_pass(const char* value, size_t size);
  ::std::string* mutable_pass();
  ::std::string* release_pass();
  void set_allocated_pass(::std::string* pass);

  // @@protoc_insertion_point(class_scope:login.Login_EmailLogin_Request_22)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr email_;
  ::google::protobuf::internal::ArenaStringPtr pass_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static Login_EmailLogin_Request_22* default_instance_;
};
// -------------------------------------------------------------------

class Login_EmailLogin_Response_22 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_EmailLogin_Response_22) */ {
 public:
  Login_EmailLogin_Response_22();
  virtual ~Login_EmailLogin_Response_22();

  Login_EmailLogin_Response_22(const Login_EmailLogin_Response_22& from);

  inline Login_EmailLogin_Response_22& operator=(const Login_EmailLogin_Response_22& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_EmailLogin_Response_22& default_instance();

  void Swap(Login_EmailLogin_Response_22* other);

  // implements Message ----------------------------------------------

  inline Login_EmailLogin_Response_22* New() const { return New(NULL); }

  Login_EmailLogin_Response_22* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Login_EmailLogin_Response_22& from);
  void MergeFrom(const Login_EmailLogin_Response_22& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Login_EmailLogin_Response_22* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ErrorCode = 1;
  void clear_errorcode();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 errorcode() const;
  void set_errorcode(::google::protobuf::int32 value);

  // optional int64 userId = 2;
  void clear_userid();
  static const int kUserIdFieldNumber = 2;
  ::google::protobuf::int64 userid() const;
  void set_userid(::google::protobuf::int64 value);

  // optional string key = 3;
  void clear_key();
  static const int kKeyFieldNumber = 3;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // optional string ip = 4;
  void clear_ip();
  static const int kIpFieldNumber = 4;
  const ::std::string& ip() const;
  void set_ip(const ::std::string& value);
  void set_ip(const char* value);
  void set_ip(const char* value, size_t size);
  ::std::string* mutable_ip();
  ::std::string* release_ip();
  void set_allocated_ip(::std::string* ip);

  // optional int32 port = 5;
  void clear_port();
  static const int kPortFieldNumber = 5;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:login.Login_EmailLogin_Response_22)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 userid_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::int32 errorcode_;
  ::google::protobuf::int32 port_;
  ::google::protobuf::internal::ArenaStringPtr ip_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static Login_EmailLogin_Response_22* default_instance_;
};
// -------------------------------------------------------------------

class Login_keyLogin_Request_25 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_keyLogin_Request_25) */ {
 public:
  Login_keyLogin_Request_25();
  virtual ~Login_keyLogin_Request_25();

  Login_keyLogin_Request_25(const Login_keyLogin_Request_25& from);

  inline Login_keyLogin_Request_25& operator=(const Login_keyLogin_Request_25& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_keyLogin_Request_25& default_instance();

  void Swap(Login_keyLogin_Request_25* other);

  // implements Message ----------------------------------------------

  inline Login_keyLogin_Request_25* New() const { return New(NULL); }

  Login_keyLogin_Request_25* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Login_keyLogin_Request_25& from);
  void MergeFrom(const Login_keyLogin_Request_25& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Login_keyLogin_Request_25* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 userId = 1;
  void clear_userid();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::int64 userid() const;
  void set_userid(::google::protobuf::int64 value);

  // optional string key = 2;
  void clear_key();
  static const int kKeyFieldNumber = 2;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // @@protoc_insertion_point(class_scope:login.Login_keyLogin_Request_25)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 userid_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static Login_keyLogin_Request_25* default_instance_;
};
// -------------------------------------------------------------------

class Login_keyLogin_Response_25 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:login.Login_keyLogin_Response_25) */ {
 public:
  Login_keyLogin_Response_25();
  virtual ~Login_keyLogin_Response_25();

  Login_keyLogin_Response_25(const Login_keyLogin_Response_25& from);

  inline Login_keyLogin_Response_25& operator=(const Login_keyLogin_Response_25& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_keyLogin_Response_25& default_instance();

  void Swap(Login_keyLogin_Response_25* other);

  // implements Message ----------------------------------------------

  inline Login_keyLogin_Response_25* New() const { return New(NULL); }

  Login_keyLogin_Response_25* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Login_keyLogin_Response_25& from);
  void MergeFrom(const Login_keyLogin_Response_25& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Login_keyLogin_Response_25* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ErrorCode = 1;
  void clear_errorcode();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 errorcode() const;
  void set_errorcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:login.Login_keyLogin_Response_25)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 errorcode_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static Login_keyLogin_Response_25* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Login_GetEmailCode_Request_1

// optional string email = 1;
inline void Login_GetEmailCode_Request_1::clear_email() {
  email_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_GetEmailCode_Request_1::email() const {
  // @@protoc_insertion_point(field_get:login.Login_GetEmailCode_Request_1.email)
  return email_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_GetEmailCode_Request_1::set_email(const ::std::string& value) {
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_GetEmailCode_Request_1.email)
}
inline void Login_GetEmailCode_Request_1::set_email(const char* value) {
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_GetEmailCode_Request_1.email)
}
inline void Login_GetEmailCode_Request_1::set_email(const char* value, size_t size) {
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_GetEmailCode_Request_1.email)
}
inline ::std::string* Login_GetEmailCode_Request_1::mutable_email() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_GetEmailCode_Request_1.email)
  return email_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_GetEmailCode_Request_1::release_email() {
  // @@protoc_insertion_point(field_release:login.Login_GetEmailCode_Request_1.email)
  
  return email_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_GetEmailCode_Request_1::set_allocated_email(::std::string* email) {
  if (email != NULL) {
    
  } else {
    
  }
  email_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), email);
  // @@protoc_insertion_point(field_set_allocated:login.Login_GetEmailCode_Request_1.email)
}

// -------------------------------------------------------------------

// Login_GetEmailCode_Response_1

// optional int32 ErrorCode = 1;
inline void Login_GetEmailCode_Response_1::clear_errorcode() {
  errorcode_ = 0;
}
inline ::google::protobuf::int32 Login_GetEmailCode_Response_1::errorcode() const {
  // @@protoc_insertion_point(field_get:login.Login_GetEmailCode_Response_1.ErrorCode)
  return errorcode_;
}
inline void Login_GetEmailCode_Response_1::set_errorcode(::google::protobuf::int32 value) {
  
  errorcode_ = value;
  // @@protoc_insertion_point(field_set:login.Login_GetEmailCode_Response_1.ErrorCode)
}

// -------------------------------------------------------------------

// Login_RegisterEmail_Request_11

// optional string code = 1;
inline void Login_RegisterEmail_Request_11::clear_code() {
  code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_RegisterEmail_Request_11::code() const {
  // @@protoc_insertion_point(field_get:login.Login_RegisterEmail_Request_11.code)
  return code_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_RegisterEmail_Request_11::set_code(const ::std::string& value) {
  
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_RegisterEmail_Request_11.code)
}
inline void Login_RegisterEmail_Request_11::set_code(const char* value) {
  
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_RegisterEmail_Request_11.code)
}
inline void Login_RegisterEmail_Request_11::set_code(const char* value, size_t size) {
  
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_RegisterEmail_Request_11.code)
}
inline ::std::string* Login_RegisterEmail_Request_11::mutable_code() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_RegisterEmail_Request_11.code)
  return code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_RegisterEmail_Request_11::release_code() {
  // @@protoc_insertion_point(field_release:login.Login_RegisterEmail_Request_11.code)
  
  return code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_RegisterEmail_Request_11::set_allocated_code(::std::string* code) {
  if (code != NULL) {
    
  } else {
    
  }
  code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), code);
  // @@protoc_insertion_point(field_set_allocated:login.Login_RegisterEmail_Request_11.code)
}

// optional string email = 2;
inline void Login_RegisterEmail_Request_11::clear_email() {
  email_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_RegisterEmail_Request_11::email() const {
  // @@protoc_insertion_point(field_get:login.Login_RegisterEmail_Request_11.email)
  return email_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_RegisterEmail_Request_11::set_email(const ::std::string& value) {
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_RegisterEmail_Request_11.email)
}
inline void Login_RegisterEmail_Request_11::set_email(const char* value) {
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_RegisterEmail_Request_11.email)
}
inline void Login_RegisterEmail_Request_11::set_email(const char* value, size_t size) {
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_RegisterEmail_Request_11.email)
}
inline ::std::string* Login_RegisterEmail_Request_11::mutable_email() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_RegisterEmail_Request_11.email)
  return email_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_RegisterEmail_Request_11::release_email() {
  // @@protoc_insertion_point(field_release:login.Login_RegisterEmail_Request_11.email)
  
  return email_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_RegisterEmail_Request_11::set_allocated_email(::std::string* email) {
  if (email != NULL) {
    
  } else {
    
  }
  email_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), email);
  // @@protoc_insertion_point(field_set_allocated:login.Login_RegisterEmail_Request_11.email)
}

// optional string name = 3;
inline void Login_RegisterEmail_Request_11::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_RegisterEmail_Request_11::name() const {
  // @@protoc_insertion_point(field_get:login.Login_RegisterEmail_Request_11.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_RegisterEmail_Request_11::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_RegisterEmail_Request_11.name)
}
inline void Login_RegisterEmail_Request_11::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_RegisterEmail_Request_11.name)
}
inline void Login_RegisterEmail_Request_11::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_RegisterEmail_Request_11.name)
}
inline ::std::string* Login_RegisterEmail_Request_11::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_RegisterEmail_Request_11.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_RegisterEmail_Request_11::release_name() {
  // @@protoc_insertion_point(field_release:login.Login_RegisterEmail_Request_11.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_RegisterEmail_Request_11::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:login.Login_RegisterEmail_Request_11.name)
}

// optional string pass = 4;
inline void Login_RegisterEmail_Request_11::clear_pass() {
  pass_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_RegisterEmail_Request_11::pass() const {
  // @@protoc_insertion_point(field_get:login.Login_RegisterEmail_Request_11.pass)
  return pass_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_RegisterEmail_Request_11::set_pass(const ::std::string& value) {
  
  pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_RegisterEmail_Request_11.pass)
}
inline void Login_RegisterEmail_Request_11::set_pass(const char* value) {
  
  pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_RegisterEmail_Request_11.pass)
}
inline void Login_RegisterEmail_Request_11::set_pass(const char* value, size_t size) {
  
  pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_RegisterEmail_Request_11.pass)
}
inline ::std::string* Login_RegisterEmail_Request_11::mutable_pass() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_RegisterEmail_Request_11.pass)
  return pass_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_RegisterEmail_Request_11::release_pass() {
  // @@protoc_insertion_point(field_release:login.Login_RegisterEmail_Request_11.pass)
  
  return pass_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_RegisterEmail_Request_11::set_allocated_pass(::std::string* pass) {
  if (pass != NULL) {
    
  } else {
    
  }
  pass_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pass);
  // @@protoc_insertion_point(field_set_allocated:login.Login_RegisterEmail_Request_11.pass)
}

// -------------------------------------------------------------------

// Login_RegisterEmail_Response_11

// optional int32 ErrorCode = 1;
inline void Login_RegisterEmail_Response_11::clear_errorcode() {
  errorcode_ = 0;
}
inline ::google::protobuf::int32 Login_RegisterEmail_Response_11::errorcode() const {
  // @@protoc_insertion_point(field_get:login.Login_RegisterEmail_Response_11.ErrorCode)
  return errorcode_;
}
inline void Login_RegisterEmail_Response_11::set_errorcode(::google::protobuf::int32 value) {
  
  errorcode_ = value;
  // @@protoc_insertion_point(field_set:login.Login_RegisterEmail_Response_11.ErrorCode)
}

// optional int64 userId = 2;
inline void Login_RegisterEmail_Response_11::clear_userid() {
  userid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Login_RegisterEmail_Response_11::userid() const {
  // @@protoc_insertion_point(field_get:login.Login_RegisterEmail_Response_11.userId)
  return userid_;
}
inline void Login_RegisterEmail_Response_11::set_userid(::google::protobuf::int64 value) {
  
  userid_ = value;
  // @@protoc_insertion_point(field_set:login.Login_RegisterEmail_Response_11.userId)
}

// -------------------------------------------------------------------

// Login_UserIdLogin_Request_21

// optional int64 userId = 1;
inline void Login_UserIdLogin_Request_21::clear_userid() {
  userid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Login_UserIdLogin_Request_21::userid() const {
  // @@protoc_insertion_point(field_get:login.Login_UserIdLogin_Request_21.userId)
  return userid_;
}
inline void Login_UserIdLogin_Request_21::set_userid(::google::protobuf::int64 value) {
  
  userid_ = value;
  // @@protoc_insertion_point(field_set:login.Login_UserIdLogin_Request_21.userId)
}

// optional string pass = 2;
inline void Login_UserIdLogin_Request_21::clear_pass() {
  pass_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_UserIdLogin_Request_21::pass() const {
  // @@protoc_insertion_point(field_get:login.Login_UserIdLogin_Request_21.pass)
  return pass_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_UserIdLogin_Request_21::set_pass(const ::std::string& value) {
  
  pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_UserIdLogin_Request_21.pass)
}
inline void Login_UserIdLogin_Request_21::set_pass(const char* value) {
  
  pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_UserIdLogin_Request_21.pass)
}
inline void Login_UserIdLogin_Request_21::set_pass(const char* value, size_t size) {
  
  pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_UserIdLogin_Request_21.pass)
}
inline ::std::string* Login_UserIdLogin_Request_21::mutable_pass() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_UserIdLogin_Request_21.pass)
  return pass_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_UserIdLogin_Request_21::release_pass() {
  // @@protoc_insertion_point(field_release:login.Login_UserIdLogin_Request_21.pass)
  
  return pass_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_UserIdLogin_Request_21::set_allocated_pass(::std::string* pass) {
  if (pass != NULL) {
    
  } else {
    
  }
  pass_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pass);
  // @@protoc_insertion_point(field_set_allocated:login.Login_UserIdLogin_Request_21.pass)
}

// -------------------------------------------------------------------

// Login_UserIdLogin_Response_21

// optional int32 ErrorCode = 1;
inline void Login_UserIdLogin_Response_21::clear_errorcode() {
  errorcode_ = 0;
}
inline ::google::protobuf::int32 Login_UserIdLogin_Response_21::errorcode() const {
  // @@protoc_insertion_point(field_get:login.Login_UserIdLogin_Response_21.ErrorCode)
  return errorcode_;
}
inline void Login_UserIdLogin_Response_21::set_errorcode(::google::protobuf::int32 value) {
  
  errorcode_ = value;
  // @@protoc_insertion_point(field_set:login.Login_UserIdLogin_Response_21.ErrorCode)
}

// optional int64 userId = 2;
inline void Login_UserIdLogin_Response_21::clear_userid() {
  userid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Login_UserIdLogin_Response_21::userid() const {
  // @@protoc_insertion_point(field_get:login.Login_UserIdLogin_Response_21.userId)
  return userid_;
}
inline void Login_UserIdLogin_Response_21::set_userid(::google::protobuf::int64 value) {
  
  userid_ = value;
  // @@protoc_insertion_point(field_set:login.Login_UserIdLogin_Response_21.userId)
}

// optional string key = 3;
inline void Login_UserIdLogin_Response_21::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_UserIdLogin_Response_21::key() const {
  // @@protoc_insertion_point(field_get:login.Login_UserIdLogin_Response_21.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_UserIdLogin_Response_21::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_UserIdLogin_Response_21.key)
}
inline void Login_UserIdLogin_Response_21::set_key(const char* value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_UserIdLogin_Response_21.key)
}
inline void Login_UserIdLogin_Response_21::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_UserIdLogin_Response_21.key)
}
inline ::std::string* Login_UserIdLogin_Response_21::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_UserIdLogin_Response_21.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_UserIdLogin_Response_21::release_key() {
  // @@protoc_insertion_point(field_release:login.Login_UserIdLogin_Response_21.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_UserIdLogin_Response_21::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:login.Login_UserIdLogin_Response_21.key)
}

// optional string ip = 4;
inline void Login_UserIdLogin_Response_21::clear_ip() {
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_UserIdLogin_Response_21::ip() const {
  // @@protoc_insertion_point(field_get:login.Login_UserIdLogin_Response_21.ip)
  return ip_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_UserIdLogin_Response_21::set_ip(const ::std::string& value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_UserIdLogin_Response_21.ip)
}
inline void Login_UserIdLogin_Response_21::set_ip(const char* value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_UserIdLogin_Response_21.ip)
}
inline void Login_UserIdLogin_Response_21::set_ip(const char* value, size_t size) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_UserIdLogin_Response_21.ip)
}
inline ::std::string* Login_UserIdLogin_Response_21::mutable_ip() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_UserIdLogin_Response_21.ip)
  return ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_UserIdLogin_Response_21::release_ip() {
  // @@protoc_insertion_point(field_release:login.Login_UserIdLogin_Response_21.ip)
  
  return ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_UserIdLogin_Response_21::set_allocated_ip(::std::string* ip) {
  if (ip != NULL) {
    
  } else {
    
  }
  ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:login.Login_UserIdLogin_Response_21.ip)
}

// optional uint32 port = 5;
inline void Login_UserIdLogin_Response_21::clear_port() {
  port_ = 0u;
}
inline ::google::protobuf::uint32 Login_UserIdLogin_Response_21::port() const {
  // @@protoc_insertion_point(field_get:login.Login_UserIdLogin_Response_21.port)
  return port_;
}
inline void Login_UserIdLogin_Response_21::set_port(::google::protobuf::uint32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:login.Login_UserIdLogin_Response_21.port)
}

// -------------------------------------------------------------------

// Login_EmailLogin_Request_22

// optional string email = 1;
inline void Login_EmailLogin_Request_22::clear_email() {
  email_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_EmailLogin_Request_22::email() const {
  // @@protoc_insertion_point(field_get:login.Login_EmailLogin_Request_22.email)
  return email_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_EmailLogin_Request_22::set_email(const ::std::string& value) {
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_EmailLogin_Request_22.email)
}
inline void Login_EmailLogin_Request_22::set_email(const char* value) {
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_EmailLogin_Request_22.email)
}
inline void Login_EmailLogin_Request_22::set_email(const char* value, size_t size) {
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_EmailLogin_Request_22.email)
}
inline ::std::string* Login_EmailLogin_Request_22::mutable_email() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_EmailLogin_Request_22.email)
  return email_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_EmailLogin_Request_22::release_email() {
  // @@protoc_insertion_point(field_release:login.Login_EmailLogin_Request_22.email)
  
  return email_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_EmailLogin_Request_22::set_allocated_email(::std::string* email) {
  if (email != NULL) {
    
  } else {
    
  }
  email_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), email);
  // @@protoc_insertion_point(field_set_allocated:login.Login_EmailLogin_Request_22.email)
}

// optional string pass = 2;
inline void Login_EmailLogin_Request_22::clear_pass() {
  pass_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_EmailLogin_Request_22::pass() const {
  // @@protoc_insertion_point(field_get:login.Login_EmailLogin_Request_22.pass)
  return pass_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_EmailLogin_Request_22::set_pass(const ::std::string& value) {
  
  pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_EmailLogin_Request_22.pass)
}
inline void Login_EmailLogin_Request_22::set_pass(const char* value) {
  
  pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_EmailLogin_Request_22.pass)
}
inline void Login_EmailLogin_Request_22::set_pass(const char* value, size_t size) {
  
  pass_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_EmailLogin_Request_22.pass)
}
inline ::std::string* Login_EmailLogin_Request_22::mutable_pass() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_EmailLogin_Request_22.pass)
  return pass_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_EmailLogin_Request_22::release_pass() {
  // @@protoc_insertion_point(field_release:login.Login_EmailLogin_Request_22.pass)
  
  return pass_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_EmailLogin_Request_22::set_allocated_pass(::std::string* pass) {
  if (pass != NULL) {
    
  } else {
    
  }
  pass_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pass);
  // @@protoc_insertion_point(field_set_allocated:login.Login_EmailLogin_Request_22.pass)
}

// -------------------------------------------------------------------

// Login_EmailLogin_Response_22

// optional int32 ErrorCode = 1;
inline void Login_EmailLogin_Response_22::clear_errorcode() {
  errorcode_ = 0;
}
inline ::google::protobuf::int32 Login_EmailLogin_Response_22::errorcode() const {
  // @@protoc_insertion_point(field_get:login.Login_EmailLogin_Response_22.ErrorCode)
  return errorcode_;
}
inline void Login_EmailLogin_Response_22::set_errorcode(::google::protobuf::int32 value) {
  
  errorcode_ = value;
  // @@protoc_insertion_point(field_set:login.Login_EmailLogin_Response_22.ErrorCode)
}

// optional int64 userId = 2;
inline void Login_EmailLogin_Response_22::clear_userid() {
  userid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Login_EmailLogin_Response_22::userid() const {
  // @@protoc_insertion_point(field_get:login.Login_EmailLogin_Response_22.userId)
  return userid_;
}
inline void Login_EmailLogin_Response_22::set_userid(::google::protobuf::int64 value) {
  
  userid_ = value;
  // @@protoc_insertion_point(field_set:login.Login_EmailLogin_Response_22.userId)
}

// optional string key = 3;
inline void Login_EmailLogin_Response_22::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_EmailLogin_Response_22::key() const {
  // @@protoc_insertion_point(field_get:login.Login_EmailLogin_Response_22.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_EmailLogin_Response_22::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_EmailLogin_Response_22.key)
}
inline void Login_EmailLogin_Response_22::set_key(const char* value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_EmailLogin_Response_22.key)
}
inline void Login_EmailLogin_Response_22::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_EmailLogin_Response_22.key)
}
inline ::std::string* Login_EmailLogin_Response_22::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_EmailLogin_Response_22.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_EmailLogin_Response_22::release_key() {
  // @@protoc_insertion_point(field_release:login.Login_EmailLogin_Response_22.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_EmailLogin_Response_22::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:login.Login_EmailLogin_Response_22.key)
}

// optional string ip = 4;
inline void Login_EmailLogin_Response_22::clear_ip() {
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_EmailLogin_Response_22::ip() const {
  // @@protoc_insertion_point(field_get:login.Login_EmailLogin_Response_22.ip)
  return ip_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_EmailLogin_Response_22::set_ip(const ::std::string& value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_EmailLogin_Response_22.ip)
}
inline void Login_EmailLogin_Response_22::set_ip(const char* value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_EmailLogin_Response_22.ip)
}
inline void Login_EmailLogin_Response_22::set_ip(const char* value, size_t size) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_EmailLogin_Response_22.ip)
}
inline ::std::string* Login_EmailLogin_Response_22::mutable_ip() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_EmailLogin_Response_22.ip)
  return ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_EmailLogin_Response_22::release_ip() {
  // @@protoc_insertion_point(field_release:login.Login_EmailLogin_Response_22.ip)
  
  return ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_EmailLogin_Response_22::set_allocated_ip(::std::string* ip) {
  if (ip != NULL) {
    
  } else {
    
  }
  ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:login.Login_EmailLogin_Response_22.ip)
}

// optional int32 port = 5;
inline void Login_EmailLogin_Response_22::clear_port() {
  port_ = 0;
}
inline ::google::protobuf::int32 Login_EmailLogin_Response_22::port() const {
  // @@protoc_insertion_point(field_get:login.Login_EmailLogin_Response_22.port)
  return port_;
}
inline void Login_EmailLogin_Response_22::set_port(::google::protobuf::int32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:login.Login_EmailLogin_Response_22.port)
}

// -------------------------------------------------------------------

// Login_keyLogin_Request_25

// optional int64 userId = 1;
inline void Login_keyLogin_Request_25::clear_userid() {
  userid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Login_keyLogin_Request_25::userid() const {
  // @@protoc_insertion_point(field_get:login.Login_keyLogin_Request_25.userId)
  return userid_;
}
inline void Login_keyLogin_Request_25::set_userid(::google::protobuf::int64 value) {
  
  userid_ = value;
  // @@protoc_insertion_point(field_set:login.Login_keyLogin_Request_25.userId)
}

// optional string key = 2;
inline void Login_keyLogin_Request_25::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Login_keyLogin_Request_25::key() const {
  // @@protoc_insertion_point(field_get:login.Login_keyLogin_Request_25.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_keyLogin_Request_25::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:login.Login_keyLogin_Request_25.key)
}
inline void Login_keyLogin_Request_25::set_key(const char* value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:login.Login_keyLogin_Request_25.key)
}
inline void Login_keyLogin_Request_25::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:login.Login_keyLogin_Request_25.key)
}
inline ::std::string* Login_keyLogin_Request_25::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:login.Login_keyLogin_Request_25.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Login_keyLogin_Request_25::release_key() {
  // @@protoc_insertion_point(field_release:login.Login_keyLogin_Request_25.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Login_keyLogin_Request_25::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:login.Login_keyLogin_Request_25.key)
}

// -------------------------------------------------------------------

// Login_keyLogin_Response_25

// optional int32 ErrorCode = 1;
inline void Login_keyLogin_Response_25::clear_errorcode() {
  errorcode_ = 0;
}
inline ::google::protobuf::int32 Login_keyLogin_Response_25::errorcode() const {
  // @@protoc_insertion_point(field_get:login.Login_keyLogin_Response_25.ErrorCode)
  return errorcode_;
}
inline void Login_keyLogin_Response_25::set_errorcode(::google::protobuf::int32 value) {
  
  errorcode_ = value;
  // @@protoc_insertion_point(field_set:login.Login_keyLogin_Response_25.ErrorCode)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace login

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_login_2eproto__INCLUDED
